// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	http "github.com/JulianoL13/app-proxy-engine/internal/proxy/http"
	mock "github.com/stretchr/testify/mock"
)

// GetProxiesUseCase is an autogenerated mock type for the GetProxiesUseCase type
type GetProxiesUseCase struct {
	mock.Mock
}

type GetProxiesUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *GetProxiesUseCase) EXPECT() *GetProxiesUseCase_Expecter {
	return &GetProxiesUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, input
func (_m *GetProxiesUseCase) Execute(ctx context.Context, input http.GetProxiesInput) (http.GetProxiesOutput, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 http.GetProxiesOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, http.GetProxiesInput) (http.GetProxiesOutput, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, http.GetProxiesInput) http.GetProxiesOutput); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(http.GetProxiesOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, http.GetProxiesInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProxiesUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type GetProxiesUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input http.GetProxiesInput
func (_e *GetProxiesUseCase_Expecter) Execute(ctx interface{}, input interface{}) *GetProxiesUseCase_Execute_Call {
	return &GetProxiesUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *GetProxiesUseCase_Execute_Call) Run(run func(ctx context.Context, input http.GetProxiesInput)) *GetProxiesUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(http.GetProxiesInput))
	})
	return _c
}

func (_c *GetProxiesUseCase_Execute_Call) Return(_a0 http.GetProxiesOutput, _a1 error) *GetProxiesUseCase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GetProxiesUseCase_Execute_Call) RunAndReturn(run func(context.Context, http.GetProxiesInput) (http.GetProxiesOutput, error)) *GetProxiesUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewGetProxiesUseCase creates a new instance of GetProxiesUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetProxiesUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetProxiesUseCase {
	mock := &GetProxiesUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
