// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	proxy "github.com/JulianoL13/app-proxy-engine/internal/proxy"
)

// GetRandomProxyUseCase is an autogenerated mock type for the GetRandomProxyUseCase type
type GetRandomProxyUseCase struct {
	mock.Mock
}

type GetRandomProxyUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *GetRandomProxyUseCase) EXPECT() *GetRandomProxyUseCase_Expecter {
	return &GetRandomProxyUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx
func (_m *GetRandomProxyUseCase) Execute(ctx context.Context) (*proxy.Proxy, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *proxy.Proxy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*proxy.Proxy, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *proxy.Proxy); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proxy.Proxy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRandomProxyUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type GetRandomProxyUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
func (_e *GetRandomProxyUseCase_Expecter) Execute(ctx interface{}) *GetRandomProxyUseCase_Execute_Call {
	return &GetRandomProxyUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx)}
}

func (_c *GetRandomProxyUseCase_Execute_Call) Run(run func(ctx context.Context)) *GetRandomProxyUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *GetRandomProxyUseCase_Execute_Call) Return(_a0 *proxy.Proxy, _a1 error) *GetRandomProxyUseCase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GetRandomProxyUseCase_Execute_Call) RunAndReturn(run func(context.Context) (*proxy.Proxy, error)) *GetRandomProxyUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewGetRandomProxyUseCase creates a new instance of GetRandomProxyUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetRandomProxyUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetRandomProxyUseCase {
	mock := &GetRandomProxyUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
