// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Cleaner is an autogenerated mock type for the Cleaner type
type Cleaner struct {
	mock.Mock
}

type Cleaner_Expecter struct {
	mock *mock.Mock
}

func (_m *Cleaner) EXPECT() *Cleaner_Expecter {
	return &Cleaner_Expecter{mock: &_m.Mock}
}

// Cleanup provides a mock function with given fields: ctx
func (_m *Cleaner) Cleanup(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Cleanup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Cleaner_Cleanup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cleanup'
type Cleaner_Cleanup_Call struct {
	*mock.Call
}

// Cleanup is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Cleaner_Expecter) Cleanup(ctx interface{}) *Cleaner_Cleanup_Call {
	return &Cleaner_Cleanup_Call{Call: _e.mock.On("Cleanup", ctx)}
}

func (_c *Cleaner_Cleanup_Call) Run(run func(ctx context.Context)) *Cleaner_Cleanup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Cleaner_Cleanup_Call) Return(_a0 error) *Cleaner_Cleanup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Cleaner_Cleanup_Call) RunAndReturn(run func(context.Context) error) *Cleaner_Cleanup_Call {
	_c.Call.Return(run)
	return _c
}

// NewCleaner creates a new instance of Cleaner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCleaner(t interface {
	mock.TestingT
	Cleanup(func())
}) *Cleaner {
	mock := &Cleaner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
