// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	scraper "github.com/JulianoL13/app-proxy-engine/internal/scraper"
	mock "github.com/stretchr/testify/mock"
)

// Fetcher is an autogenerated mock type for the Fetcher type
type Fetcher struct {
	mock.Mock
}

type Fetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *Fetcher) EXPECT() *Fetcher_Expecter {
	return &Fetcher_Expecter{mock: &_m.Mock}
}

// FetchAndParse provides a mock function with given fields: ctx, source
func (_m *Fetcher) FetchAndParse(ctx context.Context, source scraper.Source) ([]*scraper.ScrapeOutput, error) {
	ret := _m.Called(ctx, source)

	if len(ret) == 0 {
		panic("no return value specified for FetchAndParse")
	}

	var r0 []*scraper.ScrapeOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, scraper.Source) ([]*scraper.ScrapeOutput, error)); ok {
		return rf(ctx, source)
	}
	if rf, ok := ret.Get(0).(func(context.Context, scraper.Source) []*scraper.ScrapeOutput); ok {
		r0 = rf(ctx, source)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*scraper.ScrapeOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, scraper.Source) error); ok {
		r1 = rf(ctx, source)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Fetcher_FetchAndParse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAndParse'
type Fetcher_FetchAndParse_Call struct {
	*mock.Call
}

// FetchAndParse is a helper method to define mock.On call
//   - ctx context.Context
//   - source scraper.Source
func (_e *Fetcher_Expecter) FetchAndParse(ctx interface{}, source interface{}) *Fetcher_FetchAndParse_Call {
	return &Fetcher_FetchAndParse_Call{Call: _e.mock.On("FetchAndParse", ctx, source)}
}

func (_c *Fetcher_FetchAndParse_Call) Run(run func(ctx context.Context, source scraper.Source)) *Fetcher_FetchAndParse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(scraper.Source))
	})
	return _c
}

func (_c *Fetcher_FetchAndParse_Call) Return(_a0 []*scraper.ScrapeOutput, _a1 error) *Fetcher_FetchAndParse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Fetcher_FetchAndParse_Call) RunAndReturn(run func(context.Context, scraper.Source) ([]*scraper.ScrapeOutput, error)) *Fetcher_FetchAndParse_Call {
	_c.Call.Return(run)
	return _c
}

// NewFetcher creates a new instance of Fetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *Fetcher {
	mock := &Fetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
