// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	scraper "github.com/JulianoL13/app-proxy-engine/internal/scraper"
)

// ProxySerializer is an autogenerated mock type for the ProxySerializer type
type ProxySerializer struct {
	mock.Mock
}

type ProxySerializer_Expecter struct {
	mock *mock.Mock
}

func (_m *ProxySerializer) EXPECT() *ProxySerializer_Expecter {
	return &ProxySerializer_Expecter{mock: &_m.Mock}
}

// Serialize provides a mock function with given fields: p
func (_m *ProxySerializer) Serialize(p scraper.ScrapedProxy) ([]byte, error) {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Serialize")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(scraper.ScrapedProxy) ([]byte, error)); ok {
		return rf(p)
	}
	if rf, ok := ret.Get(0).(func(scraper.ScrapedProxy) []byte); ok {
		r0 = rf(p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(scraper.ScrapedProxy) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProxySerializer_Serialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Serialize'
type ProxySerializer_Serialize_Call struct {
	*mock.Call
}

// Serialize is a helper method to define mock.On call
//   - p scraper.ScrapedProxy
func (_e *ProxySerializer_Expecter) Serialize(p interface{}) *ProxySerializer_Serialize_Call {
	return &ProxySerializer_Serialize_Call{Call: _e.mock.On("Serialize", p)}
}

func (_c *ProxySerializer_Serialize_Call) Run(run func(p scraper.ScrapedProxy)) *ProxySerializer_Serialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(scraper.ScrapedProxy))
	})
	return _c
}

func (_c *ProxySerializer_Serialize_Call) Return(_a0 []byte, _a1 error) *ProxySerializer_Serialize_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProxySerializer_Serialize_Call) RunAndReturn(run func(scraper.ScrapedProxy) ([]byte, error)) *ProxySerializer_Serialize_Call {
	_c.Call.Return(run)
	return _c
}

// NewProxySerializer creates a new instance of ProxySerializer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProxySerializer(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProxySerializer {
	mock := &ProxySerializer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
