// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	scraper "github.com/JulianoL13/app-proxy-engine/internal/scraper"
)

// ProxyScraper is an autogenerated mock type for the ProxyScraper type
type ProxyScraper struct {
	mock.Mock
}

type ProxyScraper_Expecter struct {
	mock *mock.Mock
}

func (_m *ProxyScraper) EXPECT() *ProxyScraper_Expecter {
	return &ProxyScraper_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx
func (_m *ProxyScraper) Execute(ctx context.Context) ([]scraper.ScrapedProxy, []error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []scraper.ScrapedProxy
	var r1 []error
	if rf, ok := ret.Get(0).(func(context.Context) ([]scraper.ScrapedProxy, []error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []scraper.ScrapedProxy); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]scraper.ScrapedProxy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) []error); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]error)
		}
	}

	return r0, r1
}

// ProxyScraper_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ProxyScraper_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ProxyScraper_Expecter) Execute(ctx interface{}) *ProxyScraper_Execute_Call {
	return &ProxyScraper_Execute_Call{Call: _e.mock.On("Execute", ctx)}
}

func (_c *ProxyScraper_Execute_Call) Run(run func(ctx context.Context)) *ProxyScraper_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ProxyScraper_Execute_Call) Return(_a0 []scraper.ScrapedProxy, _a1 []error) *ProxyScraper_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProxyScraper_Execute_Call) RunAndReturn(run func(context.Context) ([]scraper.ScrapedProxy, []error)) *ProxyScraper_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewProxyScraper creates a new instance of ProxyScraper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProxyScraper(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProxyScraper {
	mock := &ProxyScraper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
