// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ScrapedProxy is an autogenerated mock type for the ScrapedProxy type
type ScrapedProxy struct {
	mock.Mock
}

type ScrapedProxy_Expecter struct {
	mock *mock.Mock
}

func (_m *ScrapedProxy) EXPECT() *ScrapedProxy_Expecter {
	return &ScrapedProxy_Expecter{mock: &_m.Mock}
}

// IP provides a mock function with no fields
func (_m *ScrapedProxy) IP() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IP")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ScrapedProxy_IP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IP'
type ScrapedProxy_IP_Call struct {
	*mock.Call
}

// IP is a helper method to define mock.On call
func (_e *ScrapedProxy_Expecter) IP() *ScrapedProxy_IP_Call {
	return &ScrapedProxy_IP_Call{Call: _e.mock.On("IP")}
}

func (_c *ScrapedProxy_IP_Call) Run(run func()) *ScrapedProxy_IP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ScrapedProxy_IP_Call) Return(_a0 string) *ScrapedProxy_IP_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ScrapedProxy_IP_Call) RunAndReturn(run func() string) *ScrapedProxy_IP_Call {
	_c.Call.Return(run)
	return _c
}

// Password provides a mock function with no fields
func (_m *ScrapedProxy) Password() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Password")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ScrapedProxy_Password_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Password'
type ScrapedProxy_Password_Call struct {
	*mock.Call
}

// Password is a helper method to define mock.On call
func (_e *ScrapedProxy_Expecter) Password() *ScrapedProxy_Password_Call {
	return &ScrapedProxy_Password_Call{Call: _e.mock.On("Password")}
}

func (_c *ScrapedProxy_Password_Call) Run(run func()) *ScrapedProxy_Password_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ScrapedProxy_Password_Call) Return(_a0 string) *ScrapedProxy_Password_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ScrapedProxy_Password_Call) RunAndReturn(run func() string) *ScrapedProxy_Password_Call {
	_c.Call.Return(run)
	return _c
}

// Port provides a mock function with no fields
func (_m *ScrapedProxy) Port() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Port")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// ScrapedProxy_Port_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Port'
type ScrapedProxy_Port_Call struct {
	*mock.Call
}

// Port is a helper method to define mock.On call
func (_e *ScrapedProxy_Expecter) Port() *ScrapedProxy_Port_Call {
	return &ScrapedProxy_Port_Call{Call: _e.mock.On("Port")}
}

func (_c *ScrapedProxy_Port_Call) Run(run func()) *ScrapedProxy_Port_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ScrapedProxy_Port_Call) Return(_a0 int) *ScrapedProxy_Port_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ScrapedProxy_Port_Call) RunAndReturn(run func() int) *ScrapedProxy_Port_Call {
	_c.Call.Return(run)
	return _c
}

// Protocol provides a mock function with no fields
func (_m *ScrapedProxy) Protocol() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Protocol")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ScrapedProxy_Protocol_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Protocol'
type ScrapedProxy_Protocol_Call struct {
	*mock.Call
}

// Protocol is a helper method to define mock.On call
func (_e *ScrapedProxy_Expecter) Protocol() *ScrapedProxy_Protocol_Call {
	return &ScrapedProxy_Protocol_Call{Call: _e.mock.On("Protocol")}
}

func (_c *ScrapedProxy_Protocol_Call) Run(run func()) *ScrapedProxy_Protocol_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ScrapedProxy_Protocol_Call) Return(_a0 string) *ScrapedProxy_Protocol_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ScrapedProxy_Protocol_Call) RunAndReturn(run func() string) *ScrapedProxy_Protocol_Call {
	_c.Call.Return(run)
	return _c
}

// Source provides a mock function with no fields
func (_m *ScrapedProxy) Source() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Source")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ScrapedProxy_Source_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Source'
type ScrapedProxy_Source_Call struct {
	*mock.Call
}

// Source is a helper method to define mock.On call
func (_e *ScrapedProxy_Expecter) Source() *ScrapedProxy_Source_Call {
	return &ScrapedProxy_Source_Call{Call: _e.mock.On("Source")}
}

func (_c *ScrapedProxy_Source_Call) Run(run func()) *ScrapedProxy_Source_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ScrapedProxy_Source_Call) Return(_a0 string) *ScrapedProxy_Source_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ScrapedProxy_Source_Call) RunAndReturn(run func() string) *ScrapedProxy_Source_Call {
	_c.Call.Return(run)
	return _c
}

// Username provides a mock function with no fields
func (_m *ScrapedProxy) Username() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Username")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ScrapedProxy_Username_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Username'
type ScrapedProxy_Username_Call struct {
	*mock.Call
}

// Username is a helper method to define mock.On call
func (_e *ScrapedProxy_Expecter) Username() *ScrapedProxy_Username_Call {
	return &ScrapedProxy_Username_Call{Call: _e.mock.On("Username")}
}

func (_c *ScrapedProxy_Username_Call) Run(run func()) *ScrapedProxy_Username_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ScrapedProxy_Username_Call) Return(_a0 string) *ScrapedProxy_Username_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ScrapedProxy_Username_Call) RunAndReturn(run func() string) *ScrapedProxy_Username_Call {
	_c.Call.Return(run)
	return _c
}

// NewScrapedProxy creates a new instance of ScrapedProxy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewScrapedProxy(t interface {
	mock.TestingT
	Cleanup(func())
}) *ScrapedProxy {
	mock := &ScrapedProxy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
