with-expecter: true
packages:
  github.com/JulianoL13/app-proxy-engine/internal/verifier:
    config:
      dir: internal/verifier/mocks
      outpkg: mocks
    interfaces:
      ProxyChecker: 
        config: {}
      Verifiable:
        config: {}
  github.com/JulianoL13/app-proxy-engine/internal/scraper:
    config:
      dir: internal/scraper/mocks
      outpkg: mocks
    interfaces:
      Fetcher:
        config: {}
  github.com/JulianoL13/app-proxy-engine/internal/proxy:
    config:
      dir: internal/proxy/mocks
      outpkg: mocks
    interfaces:
      ProxyDataInput:
        config: {}
      ProxySource:
        config: {}
      ProxyChecker:
        config: {}
mockname: "{{.InterfaceName}}"
filename: "{{.InterfaceName}}.go"
