// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	verifier "github.com/JulianoL13/app-proxy-engine/internal/verifier"
	mock "github.com/stretchr/testify/mock"
)

// Consumer is an autogenerated mock type for the Consumer type
type Consumer struct {
	mock.Mock
}

type Consumer_Expecter struct {
	mock *mock.Mock
}

func (_m *Consumer) EXPECT() *Consumer_Expecter {
	return &Consumer_Expecter{mock: &_m.Mock}
}

// Ack provides a mock function with given fields: ctx, topic, group, msgID
func (_m *Consumer) Ack(ctx context.Context, topic string, group string, msgID string) error {
	ret := _m.Called(ctx, topic, group, msgID)

	if len(ret) == 0 {
		panic("no return value specified for Ack")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, topic, group, msgID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Consumer_Ack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ack'
type Consumer_Ack_Call struct {
	*mock.Call
}

// Ack is a helper method to define mock.On call
//   - ctx context.Context
//   - topic string
//   - group string
//   - msgID string
func (_e *Consumer_Expecter) Ack(ctx interface{}, topic interface{}, group interface{}, msgID interface{}) *Consumer_Ack_Call {
	return &Consumer_Ack_Call{Call: _e.mock.On("Ack", ctx, topic, group, msgID)}
}

func (_c *Consumer_Ack_Call) Run(run func(ctx context.Context, topic string, group string, msgID string)) *Consumer_Ack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *Consumer_Ack_Call) Return(_a0 error) *Consumer_Ack_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Consumer_Ack_Call) RunAndReturn(run func(context.Context, string, string, string) error) *Consumer_Ack_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function with given fields: ctx, topic, group, consumer
func (_m *Consumer) Subscribe(ctx context.Context, topic string, group string, consumer string) (<-chan verifier.Message, error) {
	ret := _m.Called(ctx, topic, group, consumer)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 <-chan verifier.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (<-chan verifier.Message, error)); ok {
		return rf(ctx, topic, group, consumer)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) <-chan verifier.Message); ok {
		r0 = rf(ctx, topic, group, consumer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan verifier.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, topic, group, consumer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Consumer_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type Consumer_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - topic string
//   - group string
//   - consumer string
func (_e *Consumer_Expecter) Subscribe(ctx interface{}, topic interface{}, group interface{}, consumer interface{}) *Consumer_Subscribe_Call {
	return &Consumer_Subscribe_Call{Call: _e.mock.On("Subscribe", ctx, topic, group, consumer)}
}

func (_c *Consumer_Subscribe_Call) Run(run func(ctx context.Context, topic string, group string, consumer string)) *Consumer_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *Consumer_Subscribe_Call) Return(_a0 <-chan verifier.Message, _a1 error) *Consumer_Subscribe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Consumer_Subscribe_Call) RunAndReturn(run func(context.Context, string, string, string) (<-chan verifier.Message, error)) *Consumer_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewConsumer creates a new instance of Consumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Consumer {
	mock := &Consumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
