// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	verifier "github.com/JulianoL13/app-proxy-engine/internal/verifier"
	mock "github.com/stretchr/testify/mock"
)

// ProxyDeserializer is an autogenerated mock type for the ProxyDeserializer type
type ProxyDeserializer struct {
	mock.Mock
}

type ProxyDeserializer_Expecter struct {
	mock *mock.Mock
}

func (_m *ProxyDeserializer) EXPECT() *ProxyDeserializer_Expecter {
	return &ProxyDeserializer_Expecter{mock: &_m.Mock}
}

// Deserialize provides a mock function with given fields: payload
func (_m *ProxyDeserializer) Deserialize(payload []byte) (verifier.VerifiedProxy, error) {
	ret := _m.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for Deserialize")
	}

	var r0 verifier.VerifiedProxy
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (verifier.VerifiedProxy, error)); ok {
		return rf(payload)
	}
	if rf, ok := ret.Get(0).(func([]byte) verifier.VerifiedProxy); ok {
		r0 = rf(payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(verifier.VerifiedProxy)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProxyDeserializer_Deserialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deserialize'
type ProxyDeserializer_Deserialize_Call struct {
	*mock.Call
}

// Deserialize is a helper method to define mock.On call
//   - payload []byte
func (_e *ProxyDeserializer_Expecter) Deserialize(payload interface{}) *ProxyDeserializer_Deserialize_Call {
	return &ProxyDeserializer_Deserialize_Call{Call: _e.mock.On("Deserialize", payload)}
}

func (_c *ProxyDeserializer_Deserialize_Call) Run(run func(payload []byte)) *ProxyDeserializer_Deserialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *ProxyDeserializer_Deserialize_Call) Return(_a0 verifier.VerifiedProxy, _a1 error) *ProxyDeserializer_Deserialize_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProxyDeserializer_Deserialize_Call) RunAndReturn(run func([]byte) (verifier.VerifiedProxy, error)) *ProxyDeserializer_Deserialize_Call {
	_c.Call.Return(run)
	return _c
}

// NewProxyDeserializer creates a new instance of ProxyDeserializer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProxyDeserializer(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProxyDeserializer {
	mock := &ProxyDeserializer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
