// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	verifier "github.com/JulianoL13/app-proxy-engine/internal/verifier"
	mock "github.com/stretchr/testify/mock"
)

// ProxyChecker is an autogenerated mock type for the ProxyChecker type
type ProxyChecker struct {
	mock.Mock
}

type ProxyChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *ProxyChecker) EXPECT() *ProxyChecker_Expecter {
	return &ProxyChecker_Expecter{mock: &_m.Mock}
}

// Verify provides a mock function with given fields: ctx, p
func (_m *ProxyChecker) Verify(ctx context.Context, p verifier.Verifiable) verifier.VerifyOutput {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 verifier.VerifyOutput
	if rf, ok := ret.Get(0).(func(context.Context, verifier.Verifiable) verifier.VerifyOutput); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Get(0).(verifier.VerifyOutput)
	}

	return r0
}

// ProxyChecker_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type ProxyChecker_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - p verifier.Verifiable
func (_e *ProxyChecker_Expecter) Verify(ctx interface{}, p interface{}) *ProxyChecker_Verify_Call {
	return &ProxyChecker_Verify_Call{Call: _e.mock.On("Verify", ctx, p)}
}

func (_c *ProxyChecker_Verify_Call) Run(run func(ctx context.Context, p verifier.Verifiable)) *ProxyChecker_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(verifier.Verifiable))
	})
	return _c
}

func (_c *ProxyChecker_Verify_Call) Return(_a0 verifier.VerifyOutput) *ProxyChecker_Verify_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProxyChecker_Verify_Call) RunAndReturn(run func(context.Context, verifier.Verifiable) verifier.VerifyOutput) *ProxyChecker_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewProxyChecker creates a new instance of ProxyChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProxyChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProxyChecker {
	mock := &ProxyChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
