// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"

	url "net/url"
)

// VerifiedProxy is an autogenerated mock type for the VerifiedProxy type
type VerifiedProxy struct {
	mock.Mock
}

type VerifiedProxy_Expecter struct {
	mock *mock.Mock
}

func (_m *VerifiedProxy) EXPECT() *VerifiedProxy_Expecter {
	return &VerifiedProxy_Expecter{mock: &_m.Mock}
}

// Address provides a mock function with no fields
func (_m *VerifiedProxy) Address() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// VerifiedProxy_Address_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Address'
type VerifiedProxy_Address_Call struct {
	*mock.Call
}

// Address is a helper method to define mock.On call
func (_e *VerifiedProxy_Expecter) Address() *VerifiedProxy_Address_Call {
	return &VerifiedProxy_Address_Call{Call: _e.mock.On("Address")}
}

func (_c *VerifiedProxy_Address_Call) Run(run func()) *VerifiedProxy_Address_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *VerifiedProxy_Address_Call) Return(_a0 string) *VerifiedProxy_Address_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VerifiedProxy_Address_Call) RunAndReturn(run func() string) *VerifiedProxy_Address_Call {
	_c.Call.Return(run)
	return _c
}

// MarkSuccess provides a mock function with given fields: latency, anonymity
func (_m *VerifiedProxy) MarkSuccess(latency time.Duration, anonymity string) {
	_m.Called(latency, anonymity)
}

// VerifiedProxy_MarkSuccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkSuccess'
type VerifiedProxy_MarkSuccess_Call struct {
	*mock.Call
}

// MarkSuccess is a helper method to define mock.On call
//   - latency time.Duration
//   - anonymity string
func (_e *VerifiedProxy_Expecter) MarkSuccess(latency interface{}, anonymity interface{}) *VerifiedProxy_MarkSuccess_Call {
	return &VerifiedProxy_MarkSuccess_Call{Call: _e.mock.On("MarkSuccess", latency, anonymity)}
}

func (_c *VerifiedProxy_MarkSuccess_Call) Run(run func(latency time.Duration, anonymity string)) *VerifiedProxy_MarkSuccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Duration), args[1].(string))
	})
	return _c
}

func (_c *VerifiedProxy_MarkSuccess_Call) Return() *VerifiedProxy_MarkSuccess_Call {
	_c.Call.Return()
	return _c
}

func (_c *VerifiedProxy_MarkSuccess_Call) RunAndReturn(run func(time.Duration, string)) *VerifiedProxy_MarkSuccess_Call {
	_c.Run(run)
	return _c
}

// URL provides a mock function with no fields
func (_m *VerifiedProxy) URL() *url.URL {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for URL")
	}

	var r0 *url.URL
	if rf, ok := ret.Get(0).(func() *url.URL); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*url.URL)
		}
	}

	return r0
}

// VerifiedProxy_URL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'URL'
type VerifiedProxy_URL_Call struct {
	*mock.Call
}

// URL is a helper method to define mock.On call
func (_e *VerifiedProxy_Expecter) URL() *VerifiedProxy_URL_Call {
	return &VerifiedProxy_URL_Call{Call: _e.mock.On("URL")}
}

func (_c *VerifiedProxy_URL_Call) Run(run func()) *VerifiedProxy_URL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *VerifiedProxy_URL_Call) Return(_a0 *url.URL) *VerifiedProxy_URL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VerifiedProxy_URL_Call) RunAndReturn(run func() *url.URL) *VerifiedProxy_URL_Call {
	_c.Call.Return(run)
	return _c
}

// NewVerifiedProxy creates a new instance of VerifiedProxy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVerifiedProxy(t interface {
	mock.TestingT
	Cleanup(func())
}) *VerifiedProxy {
	mock := &VerifiedProxy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
