// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	url "net/url"

	mock "github.com/stretchr/testify/mock"
)

// Verifiable is an autogenerated mock type for the Verifiable type
type Verifiable struct {
	mock.Mock
}

type Verifiable_Expecter struct {
	mock *mock.Mock
}

func (_m *Verifiable) EXPECT() *Verifiable_Expecter {
	return &Verifiable_Expecter{mock: &_m.Mock}
}

// Address provides a mock function with no fields
func (_m *Verifiable) Address() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Verifiable_Address_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Address'
type Verifiable_Address_Call struct {
	*mock.Call
}

// Address is a helper method to define mock.On call
func (_e *Verifiable_Expecter) Address() *Verifiable_Address_Call {
	return &Verifiable_Address_Call{Call: _e.mock.On("Address")}
}

func (_c *Verifiable_Address_Call) Run(run func()) *Verifiable_Address_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Verifiable_Address_Call) Return(_a0 string) *Verifiable_Address_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Verifiable_Address_Call) RunAndReturn(run func() string) *Verifiable_Address_Call {
	_c.Call.Return(run)
	return _c
}

// URL provides a mock function with no fields
func (_m *Verifiable) URL() *url.URL {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for URL")
	}

	var r0 *url.URL
	if rf, ok := ret.Get(0).(func() *url.URL); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*url.URL)
		}
	}

	return r0
}

// Verifiable_URL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'URL'
type Verifiable_URL_Call struct {
	*mock.Call
}

// URL is a helper method to define mock.On call
func (_e *Verifiable_Expecter) URL() *Verifiable_URL_Call {
	return &Verifiable_URL_Call{Call: _e.mock.On("URL")}
}

func (_c *Verifiable_URL_Call) Run(run func()) *Verifiable_URL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Verifiable_URL_Call) Return(_a0 *url.URL) *Verifiable_URL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Verifiable_URL_Call) RunAndReturn(run func() *url.URL) *Verifiable_URL_Call {
	_c.Call.Return(run)
	return _c
}

// NewVerifiable creates a new instance of Verifiable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVerifiable(t interface {
	mock.TestingT
	Cleanup(func())
}) *Verifiable {
	mock := &Verifiable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
