// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// WorkerPool is an autogenerated mock type for the WorkerPool type
type WorkerPool struct {
	mock.Mock
}

type WorkerPool_Expecter struct {
	mock *mock.Mock
}

func (_m *WorkerPool) EXPECT() *WorkerPool_Expecter {
	return &WorkerPool_Expecter{mock: &_m.Mock}
}

// Submit provides a mock function with given fields: ctx, job
func (_m *WorkerPool) Submit(ctx context.Context, job func(context.Context)) error {
	ret := _m.Called(ctx, job)

	if len(ret) == 0 {
		panic("no return value specified for Submit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context)) error); ok {
		r0 = rf(ctx, job)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WorkerPool_Submit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Submit'
type WorkerPool_Submit_Call struct {
	*mock.Call
}

// Submit is a helper method to define mock.On call
//   - ctx context.Context
//   - job func(context.Context)
func (_e *WorkerPool_Expecter) Submit(ctx interface{}, job interface{}) *WorkerPool_Submit_Call {
	return &WorkerPool_Submit_Call{Call: _e.mock.On("Submit", ctx, job)}
}

func (_c *WorkerPool_Submit_Call) Run(run func(ctx context.Context, job func(context.Context))) *WorkerPool_Submit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context)))
	})
	return _c
}

func (_c *WorkerPool_Submit_Call) Return(_a0 error) *WorkerPool_Submit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WorkerPool_Submit_Call) RunAndReturn(run func(context.Context, func(context.Context)) error) *WorkerPool_Submit_Call {
	_c.Call.Return(run)
	return _c
}

// NewWorkerPool creates a new instance of WorkerPool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkerPool(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkerPool {
	mock := &WorkerPool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
