// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	verifier "github.com/JulianoL13/app-proxy-engine/internal/verifier"
	mock "github.com/stretchr/testify/mock"
)

// Writer is an autogenerated mock type for the Writer type
type Writer struct {
	mock.Mock
}

type Writer_Expecter struct {
	mock *mock.Mock
}

func (_m *Writer) EXPECT() *Writer_Expecter {
	return &Writer_Expecter{mock: &_m.Mock}
}

// Save provides a mock function with given fields: ctx, p
func (_m *Writer) Save(ctx context.Context, p verifier.VerifiedProxy) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, verifier.VerifiedProxy) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Writer_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type Writer_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - p verifier.VerifiedProxy
func (_e *Writer_Expecter) Save(ctx interface{}, p interface{}) *Writer_Save_Call {
	return &Writer_Save_Call{Call: _e.mock.On("Save", ctx, p)}
}

func (_c *Writer_Save_Call) Run(run func(ctx context.Context, p verifier.VerifiedProxy)) *Writer_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(verifier.VerifiedProxy))
	})
	return _c
}

func (_c *Writer_Save_Call) Return(_a0 error) *Writer_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Writer_Save_Call) RunAndReturn(run func(context.Context, verifier.VerifiedProxy) error) *Writer_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewWriter creates a new instance of Writer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Writer {
	mock := &Writer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
