// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	proxy "github.com/JulianoL13/app-proxy-engine/internal/proxy"
	mock "github.com/stretchr/testify/mock"
)

// ProxyChecker is an autogenerated mock type for the ProxyChecker type
type ProxyChecker struct {
	mock.Mock
}

type ProxyChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *ProxyChecker) EXPECT() *ProxyChecker_Expecter {
	return &ProxyChecker_Expecter{mock: &_m.Mock}
}

// Check provides a mock function with given fields: ctx, proxies
func (_m *ProxyChecker) Check(ctx context.Context, proxies []*proxy.Proxy) <-chan proxy.CheckStreamResult {
	ret := _m.Called(ctx, proxies)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 <-chan proxy.CheckStreamResult
	if rf, ok := ret.Get(0).(func(context.Context, []*proxy.Proxy) <-chan proxy.CheckStreamResult); ok {
		r0 = rf(ctx, proxies)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan proxy.CheckStreamResult)
		}
	}

	return r0
}

// ProxyChecker_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type ProxyChecker_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - ctx context.Context
//   - proxies []*proxy.Proxy
func (_e *ProxyChecker_Expecter) Check(ctx interface{}, proxies interface{}) *ProxyChecker_Check_Call {
	return &ProxyChecker_Check_Call{Call: _e.mock.On("Check", ctx, proxies)}
}

func (_c *ProxyChecker_Check_Call) Run(run func(ctx context.Context, proxies []*proxy.Proxy)) *ProxyChecker_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*proxy.Proxy))
	})
	return _c
}

func (_c *ProxyChecker_Check_Call) Return(_a0 <-chan proxy.CheckStreamResult) *ProxyChecker_Check_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProxyChecker_Check_Call) RunAndReturn(run func(context.Context, []*proxy.Proxy) <-chan proxy.CheckStreamResult) *ProxyChecker_Check_Call {
	_c.Call.Return(run)
	return _c
}

// NewProxyChecker creates a new instance of ProxyChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProxyChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProxyChecker {
	mock := &ProxyChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
