// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	proxy "github.com/JulianoL13/app-proxy-engine/internal/proxy"
	mock "github.com/stretchr/testify/mock"
)

// ProxySource is an autogenerated mock type for the ProxySource type
type ProxySource struct {
	mock.Mock
}

type ProxySource_Expecter struct {
	mock *mock.Mock
}

func (_m *ProxySource) EXPECT() *ProxySource_Expecter {
	return &ProxySource_Expecter{mock: &_m.Mock}
}

// Fetch provides a mock function with given fields: ctx
func (_m *ProxySource) Fetch(ctx context.Context) ([]proxy.ProxyDataInput, []error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []proxy.ProxyDataInput
	var r1 []error
	if rf, ok := ret.Get(0).(func(context.Context) ([]proxy.ProxyDataInput, []error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []proxy.ProxyDataInput); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]proxy.ProxyDataInput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) []error); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]error)
		}
	}

	return r0, r1
}

// ProxySource_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type ProxySource_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ProxySource_Expecter) Fetch(ctx interface{}) *ProxySource_Fetch_Call {
	return &ProxySource_Fetch_Call{Call: _e.mock.On("Fetch", ctx)}
}

func (_c *ProxySource_Fetch_Call) Run(run func(ctx context.Context)) *ProxySource_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ProxySource_Fetch_Call) Return(_a0 []proxy.ProxyDataInput, _a1 []error) *ProxySource_Fetch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProxySource_Fetch_Call) RunAndReturn(run func(context.Context) ([]proxy.ProxyDataInput, []error)) *ProxySource_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// NewProxySource creates a new instance of ProxySource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProxySource(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProxySource {
	mock := &ProxySource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
