// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ProxyDataInput is an autogenerated mock type for the ProxyDataInput type
type ProxyDataInput struct {
	mock.Mock
}

type ProxyDataInput_Expecter struct {
	mock *mock.Mock
}

func (_m *ProxyDataInput) EXPECT() *ProxyDataInput_Expecter {
	return &ProxyDataInput_Expecter{mock: &_m.Mock}
}

// IP provides a mock function with no fields
func (_m *ProxyDataInput) IP() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IP")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ProxyDataInput_IP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IP'
type ProxyDataInput_IP_Call struct {
	*mock.Call
}

// IP is a helper method to define mock.On call
func (_e *ProxyDataInput_Expecter) IP() *ProxyDataInput_IP_Call {
	return &ProxyDataInput_IP_Call{Call: _e.mock.On("IP")}
}

func (_c *ProxyDataInput_IP_Call) Run(run func()) *ProxyDataInput_IP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProxyDataInput_IP_Call) Return(_a0 string) *ProxyDataInput_IP_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProxyDataInput_IP_Call) RunAndReturn(run func() string) *ProxyDataInput_IP_Call {
	_c.Call.Return(run)
	return _c
}

// Port provides a mock function with no fields
func (_m *ProxyDataInput) Port() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Port")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// ProxyDataInput_Port_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Port'
type ProxyDataInput_Port_Call struct {
	*mock.Call
}

// Port is a helper method to define mock.On call
func (_e *ProxyDataInput_Expecter) Port() *ProxyDataInput_Port_Call {
	return &ProxyDataInput_Port_Call{Call: _e.mock.On("Port")}
}

func (_c *ProxyDataInput_Port_Call) Run(run func()) *ProxyDataInput_Port_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProxyDataInput_Port_Call) Return(_a0 int) *ProxyDataInput_Port_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProxyDataInput_Port_Call) RunAndReturn(run func() int) *ProxyDataInput_Port_Call {
	_c.Call.Return(run)
	return _c
}

// Protocol provides a mock function with no fields
func (_m *ProxyDataInput) Protocol() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Protocol")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ProxyDataInput_Protocol_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Protocol'
type ProxyDataInput_Protocol_Call struct {
	*mock.Call
}

// Protocol is a helper method to define mock.On call
func (_e *ProxyDataInput_Expecter) Protocol() *ProxyDataInput_Protocol_Call {
	return &ProxyDataInput_Protocol_Call{Call: _e.mock.On("Protocol")}
}

func (_c *ProxyDataInput_Protocol_Call) Run(run func()) *ProxyDataInput_Protocol_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProxyDataInput_Protocol_Call) Return(_a0 string) *ProxyDataInput_Protocol_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProxyDataInput_Protocol_Call) RunAndReturn(run func() string) *ProxyDataInput_Protocol_Call {
	_c.Call.Return(run)
	return _c
}

// Source provides a mock function with no fields
func (_m *ProxyDataInput) Source() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Source")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ProxyDataInput_Source_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Source'
type ProxyDataInput_Source_Call struct {
	*mock.Call
}

// Source is a helper method to define mock.On call
func (_e *ProxyDataInput_Expecter) Source() *ProxyDataInput_Source_Call {
	return &ProxyDataInput_Source_Call{Call: _e.mock.On("Source")}
}

func (_c *ProxyDataInput_Source_Call) Run(run func()) *ProxyDataInput_Source_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProxyDataInput_Source_Call) Return(_a0 string) *ProxyDataInput_Source_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProxyDataInput_Source_Call) RunAndReturn(run func() string) *ProxyDataInput_Source_Call {
	_c.Call.Return(run)
	return _c
}

// NewProxyDataInput creates a new instance of ProxyDataInput. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProxyDataInput(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProxyDataInput {
	mock := &ProxyDataInput{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
